# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
   inputs:
      merge_from:
        default: "another"

jobs:
  build:

    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: echo ${{ github.event.ref }}   ${{ github.event.merge_from }}  ${{ github.event.inputs.merge_from }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.event.ref }}
     
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}  
    - name: Check output
      run: echo ${{ steps.vars.outputs.short_ref }}
    - name: Merge dev to test
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git branch --show-current
          git checkout refs/heads/main
          git branch --show-current
          ##git pull --allow-unrelated-histories
          git merge ${{ github.event.inputs.merge_from }} "Auto-merge another to test"
          git push   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: application
        path: /home/runner/work/Webpack/my-app/dist/
